export {
    site,
    forms,
    mockHeader,
    mockFooter,
    mockBranches,
    mockServiceDetails,
    getServiceDetail,
    mockPage,
    getMockSection,
    newsPage,
    NEWS_PAGE_SIZE,
    mockOffers,
    mockNews,
} from '@/content';
