import { muller, helveticaNeue, helvetica, roboto, sfPro, neueHaas } from './fonts';
import './globals.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { mockGlobal } from '@/lib/mock-data';
import { ThemeProvider } from '@/components/ThemeProvider';

const fontVariables = [
    muller.variable,
    helveticaNeue.variable,
    helvetica.variable,
    roboto.variable,
    sfPro.variable,
    neueHaas.variable,
].join(' ');

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
    return (
        <html lang="ru" className={fontVariables} suppressHydrationWarning>
            <body>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
                    <Header data={mockGlobal} />
                        {children}
                    <Footer data={mockGlobal} />
                </ThemeProvider>
            </body>
        </html>
    );
}
